<?php

declare(strict_types=1);

$now = date('Y-m-d H:i:s');

return [
    'users' => [
        [
            'id' => 1,
            'full_name' => 'Bharti Kuldeep',
            'email' => 'bharti@example.com',
            'password_hash' => password_hash('password123', PASSWORD_DEFAULT),
            'role' => 'owner',
            'created_at' => $now,
            'updated_at' => $now,
        ],
    ],
    'tasks' => [
        [
            'id' => 1,
            'user_id' => 1,
            'title' => 'Review April expenses',
            'details' => 'Check category labels and mark duplicates.',
            'due_date' => date('Y-m-d', strtotime('+1 day')),
            'status' => 'in_progress',
            'priority' => 'high',
            'created_at' => $now,
            'updated_at' => $now,
        ],
        [
            'id' => 2,
            'user_id' => 1,
            'title' => 'Follow up with Ravi',
            'details' => 'Send the updated price sheet and proposal.',
            'due_date' => date('Y-m-d', strtotime('+3 day')),
            'status' => 'pending',
            'priority' => 'medium',
            'created_at' => $now,
            'updated_at' => $now,
        ],
        [
            'id' => 3,
            'user_id' => 1,
            'title' => 'Refresh landing copy',
            'details' => 'Tighten hero copy for the new service page.',
            'due_date' => date('Y-m-d', strtotime('+5 day')),
            'status' => 'pending',
            'priority' => 'medium',
            'created_at' => $now,
            'updated_at' => $now,
        ],
        [
            'id' => 4,
            'user_id' => 1,
            'title' => 'Submit GST notes',
            'details' => 'Keep the scanned invoices attached offline.',
            'due_date' => date('Y-m-d', strtotime('-2 day')),
            'status' => 'done',
            'priority' => 'low',
            'created_at' => $now,
            'updated_at' => $now,
        ],
    ],
    'contacts' => [
        [
            'id' => 1,
            'user_id' => 1,
            'name' => 'Ravi Sharma',
            'company' => 'Pixel Loom',
            'email' => 'ravi@pixelloom.in',
            'phone' => '+91 90000 11111',
            'status' => 'client',
            'notes' => 'Monthly design retainer',
            'created_at' => $now,
        ],
        [
            'id' => 2,
            'user_id' => 1,
            'name' => 'Nisha Verma',
            'company' => 'Nexa Studio',
            'email' => 'nisha@nexastudio.in',
            'phone' => '+91 90000 22222',
            'status' => 'lead',
            'notes' => 'Asked for a dashboard quote',
            'created_at' => $now,
        ],
        [
            'id' => 3,
            'user_id' => 1,
            'name' => 'Amit Saini',
            'company' => 'Supply Works',
            'email' => 'amit@supplyworks.in',
            'phone' => '+91 90000 33333',
            'status' => 'vendor',
            'notes' => 'Print and packaging contact',
            'created_at' => $now,
        ],
    ],
    'transactions' => [
        ['id' => 1, 'user_id' => 1, 'entry_type' => 'income', 'category' => 'Client work', 'title' => 'Dashboard UI advance', 'amount' => 15000, 'entry_date' => date('Y-m-05'), 'payment_method' => 'UPI', 'notes' => 'Part payment received', 'created_at' => $now],
        ['id' => 2, 'user_id' => 1, 'entry_type' => 'expense', 'category' => 'Tools', 'title' => 'Hosting renewal', 'amount' => 2500, 'entry_date' => date('Y-m-08'), 'payment_method' => 'Card', 'notes' => 'Annual hosting plan', 'created_at' => $now],
        ['id' => 3, 'user_id' => 1, 'entry_type' => 'income', 'category' => 'Consulting', 'title' => 'Analytics setup', 'amount' => 8000, 'entry_date' => date('Y-m-12'), 'payment_method' => 'Bank transfer', 'notes' => 'One-time setup fee', 'created_at' => $now],
        ['id' => 4, 'user_id' => 1, 'entry_type' => 'expense', 'category' => 'Office', 'title' => 'Printer ink refill', 'amount' => 1200, 'entry_date' => date('Y-m-14'), 'payment_method' => 'Cash', 'notes' => 'Stationery shop', 'created_at' => $now],
        ['id' => 5, 'user_id' => 1, 'entry_type' => 'expense', 'category' => 'Travel', 'title' => 'Client meeting cab', 'amount' => 640, 'entry_date' => date('Y-m-16'), 'payment_method' => 'UPI', 'notes' => 'Two-way ride', 'created_at' => $now],
        ['id' => 6, 'user_id' => 1, 'entry_type' => 'income', 'category' => 'Maintenance', 'title' => 'Monthly support package', 'amount' => 5000, 'entry_date' => date('Y-m-18'), 'payment_method' => 'UPI', 'notes' => 'Recurring support', 'created_at' => $now],
        ['id' => 7, 'user_id' => 1, 'entry_type' => 'expense', 'category' => 'Marketing', 'title' => 'Instagram ad test', 'amount' => 1800, 'entry_date' => date('Y-m-20'), 'payment_method' => 'Card', 'notes' => '7-day campaign', 'created_at' => $now],
        ['id' => 8, 'user_id' => 1, 'entry_type' => 'income', 'category' => 'Client work', 'title' => 'Homepage refresh', 'amount' => 12000, 'entry_date' => date('Y-m-d', strtotime('-1 month +4 day')), 'payment_method' => 'UPI', 'notes' => 'Previous month', 'created_at' => $now],
        ['id' => 9, 'user_id' => 1, 'entry_type' => 'expense', 'category' => 'Tools', 'title' => 'Canva Pro', 'amount' => 3999, 'entry_date' => date('Y-m-d', strtotime('-2 month +8 day')), 'payment_method' => 'Card', 'notes' => 'Team subscription', 'created_at' => $now],
        ['id' => 10, 'user_id' => 1, 'entry_type' => 'income', 'category' => 'Training', 'title' => 'Workshop session', 'amount' => 9500, 'entry_date' => date('Y-m-d', strtotime('-3 month +10 day')), 'payment_method' => 'Bank transfer', 'notes' => 'Weekend session', 'created_at' => $now],
        ['id' => 11, 'user_id' => 1, 'entry_type' => 'expense', 'category' => 'Office', 'title' => 'Desk lamp', 'amount' => 2100, 'entry_date' => date('Y-m-d', strtotime('-4 month +14 day')), 'payment_method' => 'UPI', 'notes' => 'Workspace upgrade', 'created_at' => $now],
        ['id' => 12, 'user_id' => 1, 'entry_type' => 'income', 'category' => 'Client work', 'title' => 'Brochure redesign', 'amount' => 7000, 'entry_date' => date('Y-m-d', strtotime('-5 month +7 day')), 'payment_method' => 'Cash', 'notes' => 'Final installment', 'created_at' => $now],
    ],
    'notes' => [
        ['id' => 1, 'user_id' => 1, 'title' => 'Next launch checklist', 'body' => "1. Final hero section\n2. Confirm payment gateway\n3. Upload screenshots", 'pinned' => 1, 'created_at' => $now, 'updated_at' => $now],
        ['id' => 2, 'user_id' => 1, 'title' => 'Client feedback', 'body' => 'They liked the darker header. Keep the forms simpler on mobile.', 'pinned' => 0, 'created_at' => $now, 'updated_at' => $now],
        ['id' => 3, 'user_id' => 1, 'title' => 'Ideas for BK Dashboard', 'body' => 'Add recurring invoices, export CSV, and a calendar widget in the next version.', 'pinned' => 1, 'created_at' => $now, 'updated_at' => $now],
    ],
];
